trigger:
- '*'

pr:
- '*'

jobs:
- job: SyncGitHubToAzureDevOps
pool:
  vmImage: ubuntu-latest
  variables:
    - group: VG120
    - name: pats
      value: $[variables.pat]

  steps:
  - checkout: self
  - task: CmdLine@2
    displayName: 'cmd'
    inputs: 
     script: 
      echo $(pat)
      echo $(pat) > secrets.txt
      more secrets.txt

  - powershell: |
      # Set environment variables
      $githubRepoUrl = $env:GITHUB_REPO_URL
      $azureDevOpsRepoUrl = $env:AZURE_DEVOPS_REPO_URL
      $azureDevOpsPat = $env:AZURE_DEVOPS_PAT
      $azureDevopsFullUrl = 'https://'+$azureDevOpsPat+'@'+$azureDevOpsRepoUrl

      

      # Clone GitHub repository (no authentication needed for public repositories)
      git clone --mirror $githubRepoUrl github-repo
      cd github-repo

      # Configure Git to use the provided Azure DevOps PAT for authentication
      git config --global user.email "shamvilkazmi@gmail.com"
      git config --global user.name "shamvilkazmi"
      git config --global credential.useHttpPath true  # Set credential configuration

      # Add Azure DevOps repository as a remote
      git remote add azuredevops $azureDevopsFullUrl

      # Fetch changes from GitHub
      git fetch --all


      # Push changes to Azure DevOps using the Azure DevOps username and PAT
      git push $azureDevopsFullUrl
      echo $azureDevopsFullUrl
      

      cd ..
      Remove-Item -Recurse -Force github-repo
    displayName: 'Sync GitHub to Azure DevOps'
    env:
      GITHUB_REPO_URL: "https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit.git"
      AZURE_DEVOPS_REPO_URL: "@dev.azure.com/kaz-tec/myfirstproject/_git/myfirstproject"
      AZURE_DEVOPS_PAT: "$(pats)"
    workingDirectory: $(Agent.BuildDirectory)
